config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  root 'home#index'
  resources :stations, only: [:index, :show] do
    resources :rentals, except: [:index]
  end
  resources :records
  put '/records/:id/finalize', to: 'records#finalize'
  resources :rentals, only: [:index]
end

app/models/station.rb
# frozen_string_literal: true

# Station Model
class Station < ApplicationRecord
  resourcify

  has_many :rentals, dependent: :destroy
  has_many :records
  has_many :bikes

  validates :address, presence: true, uniqueness: true, length: { in: 10..30 }
  validates :available_bikes, presence: true
end

app/controllers/stations_controller.rb
# frozen_string_literal: true

# Stations Controller
class StationsController < ApplicationController
  load_and_authorize_resource

  def index
    @stations = Station.all
  end

  def show
    @station = Station.find(params[:id])
  end
end

app/helpers/stations_helper.rb
# frozen_string_literal: true

# Stations Helper
module StationsHelper
end

app/views/stations/_station.html.erb
<tr>
  <td><%= station.address %></td>
  <td><%= station.available_bikes %></td>
  <% if station.available_bikes > 0 %>
    <td><%= link_to 'Select', new_station_rental_path(station), class: 'btn btn-success btn-sm' %></td>
  <% else %>
    <td></td>
  <% end %>
</tr>

app/views/stations/index.html.erb
<h1>Stations</h1>

<table class="table w-50">
  <thead>
    <tr>
      <th>Address</th>
      <th>Available Bikes</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @stations.each do |station| %>
      <% cache station do %>
        <%= render station %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/stations/show.html.erb
<h1><%= @station.address %> Station</h1>

<%= render 'rentals/new' %>