config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  root 'home#index'
  resources :stations, only: [:index, :show] do
    resources :rentals, except: [:index]
  end
  resources :records
  put '/records/:id/finalize', to: 'records#finalize'
  resources :rentals, only: [:index]
end

app/models/record.rb
# frozen_string_literal: true

# Record model
class Record < ApplicationRecord
  resourcify
  include AASM

  belongs_to :rental
  belongs_to :bike
  belongs_to :station

  before_validation :assign_rental, :assign_station, :assign_bike,
                    :assign_hours, on: :create
  after_update :release_bike
  after_touch :verify_state

  validates :rental_code, presence: true, uniqueness: true

  aasm column: :state do
    state :actual, initial: true
    state :finished, :delayed

    event :finalize do
      transitions from: %i[actual delayed], to: :finished
    end

    event :delay do
      transitions from: :actual, to: :delayed
    end
  end

  def release_bike
    bike.dispose! if bike.may_dispose?
  end

  protected

  def rental_code_exist?
    Rental.exists?(code: rental_code)
  end

  def rental_of_the_code
    Rental.find_by(code: rental_code)
  end

  def assign_rental
    if rental_code_exist?
      self.rental_id = rental_of_the_code.id
    else
      errors.add(:rental_code, 'does not exist.')
    end
  end

  def station_has_bikes?
    Bike.bikes_by_station(rental.station.id).available.any?
  end

  def assign_station
    if rental_code_exist? && station_has_bikes?
      self.station_id = rental_of_the_code.station_id
    else
      errors.add(:station, 'has not bikes.')
    end
  end

  def bike_station
    Bike.bikes_by_station(station_id).available.first
  end

  def assign_bike
    if rental_code_exist? && station_has_bikes?
      self.bike_id = bike_station.id
      bike.rent!
    end
  end

  def assign_hours
    self.ends_at = DateTime.now + rental.hours.hours if rental_code_exist?
  end

  def verify_state
    delay! if ends_at.past? && state == 'actual'
  end
end

app/controllers/records_controller.rb
# frozen_string_literal: true

# Records Controller
class RecordsController < ApplicationController
  before_action :find_record, except: %i[index new create]
  load_and_authorize_resource

  def index
    @records = Record.order(:state)
    touch_records
  end

  def show
    @record.touch if @record.actual?
  end

  def finalize
    @record.finalize!
    @record.release_bike
    redirect_to records_path
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    if @record.save
      redirect_to @record
      flash[:notice] = 'Record was created successfully.'
    else
      render 'new'
      flash[:alert] = 'Record could not be created.'
    end
  end

  private

  def record_params
    params.require(:record).permit(:rental_code)
  end

  def find_record
    @record = Record.find(params[:id])
  end

  def touch_records
    @records.each do |record|
      record.touch if record.actual?
    end
  end
end

app/helpers/records_helper.rb
# frozen_string_literal: true

# Records Helper
module RecordsHelper
end

app/views/records/_record.html.erb
<tr>
  <td><%= record.rental_code %></td>
  <td><%= record.ends_at %></td>
  <td><%= record.bike.serial_number %></td>
  <td><%= record.station.address %></td>
  <td><%= record.state %></td>
  <td><%= link_to 'Show', record_path(record), class: 'btn btn-success btn-sm' %></td>
</tr>

app/views/records/index.html.erb
<div class="w-75">
  <h1 class="float-left">Records</h1>
  <%= link_to 'New record', new_record_path, class: 'btn btn-primary float-right' %>
  <table class="table">
    <thead>
      <tr>
        <th>Rental Code</th>
        <th>Ends At</th>
        <th>Bike Serial Number</th>
        <th>Station Address</th>
        <th>State</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @records.each do |record| %>
        <% cache record do %>
          <%= render record %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/records/new.html.erb
<h1 class="text-center">New Record</h1>

<div class="container w-50">
  <%= simple_form_for @record do |f| %>
    <% if @record.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>
    
        <ul>
        <% @record.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.input :rental_code %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/records/show.html.erb
<div class="container w-50 border text-center">
  <h1>Ends at: </h1>
  <h3><%= @record.ends_at %></h3>
  <h1>Bike: </h1>
  <h3><%= @record.bike.serial_number %></h3>
  <h1>State: </h1>
  <h3><%= @record.state %></h3>
  <%= link_to 'Back', records_path, class: 'btn btn-secondary' %>
  <% if @record.may_finalize? %>
    <%= link_to 'Finalize', "/records/#{@record.id}/finalize", class: 'btn btn-success', method: :put %>
  <% end %>
</div>