config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  root 'home#index'
  resources :stations, only: [:index, :show] do
    resources :rentals, except: [:index]
  end
  resources :records
  put '/records/:id/finalize', to: 'records#finalize'
  resources :rentals, only: [:index]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bykes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('bike-icon.png') %>
  </head>

  <body>
    <%- if user_signed_in? || admin_signed_in? %>
      <nav class="navbar navbar-light bg-light">
        <div class="nav">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <% if can? :read, Record %>
            <li class="nav-item">
              <%= link_to 'Records', records_path, class: 'nav-link' %>
            </li>
          <% end %>
        </div>
        <ul class="nav justify-content-end">
          <%- if user_signed_in? %>
            <% if can? :read, Rental %>
              <li class="nav-item">
                <%= link_to 'My rentals', rentals_path, class: 'btn btn-info btn-sm m-1' %>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to 'Edit profile', edit_user_registration_path, class: 'btn btn-primary btn-sm m-1' %>
            </li>
            <li class="nav-item">
              <%= link_to ' Exit', destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-sm m-1' %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to ' Exit', destroy_admin_session_path, method: :delete, class: 'btn btn-danger btn-sm m-1' %>
            </li>
          <% end %>
        </ul>
      </nav>
    <% end %>
    <div class='p-2'>
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>" role="alert">
          <%= value %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>